/// <reference types="react" />
import { IReactionDisposer } from 'mobx';
import { BaseContentItem } from './baseContentItem';
import { ContentPlaceArea } from './contentPlaceArea';
import { ITableColumnViewModel, ITableColumnViewModelCreateOptions } from './tableColumnViewModel';
import { ITableRowViewModel, ITableRowViewModelCreateOptions } from './tableRowViewModel';
import { ITableCellViewModel, ITableCellViewModelCreateOptions } from './tableCellViewModel';
import { ITableBlockViewModel, ITableBlockViewModelCreateOptions } from './tableBlockViewModel';
import type { IViewComponentBase } from '../viewComponentBase';
import type { IWorkplaceViewComponent } from '../workplaceViewComponent';
import { SchemeDbType, EventHandler } from 'tessa/platform';
import { ViewMetadataSealed, ViewColumnMetadataSealed } from 'tessa/views/metadata';
import type { MenuAction } from 'tessa/ui/menuAction';
import type { ColumnSettings, ColumnSetting } from 'tessa/views/workplaces/columnSettings';
import { IUIContext } from 'tessa/ui/uiContext';
interface ColumnInfo {
    column: ITableColumnViewModel;
    columnSetting: ColumnSetting | null;
    orderPosition: number;
}
export declare abstract class TableGridViewModelBase<T extends IViewComponentBase = IWorkplaceViewComponent> extends BaseContentItem<T> {
    constructor(viewComponent: T, area?: ContentPlaceArea, order?: number);
    protected _columnsCache: Map<string, SchemeDbType> | null;
    protected _columns: Array<ITableColumnViewModel>;
    protected _columnReaction: IReactionDisposer | null;
    protected _columnSortReaction: IReactionDisposer | null;
    protected _rows: Array<ITableRowViewModel>;
    protected _rowsReaction: IReactionDisposer | null;
    protected _columnSettings: ColumnSettings;
    private _initialized;
    protected _groupingColumn: ViewColumnMetadataSealed | null;
    protected _blocks: ITableBlockViewModel[];
    protected _canSelectMultipleItems: boolean;
    protected _saveTableHeightWhenLoading: boolean;
    protected _wideTableVisibleWidth: number;
    protected _horizontalScroll: boolean;
    get columns(): ReadonlyArray<ITableColumnViewModel>;
    get rows(): ReadonlyArray<ITableRowViewModel>;
    get visibleRows(): ReadonlyArray<ITableRowViewModel>;
    get blocks(): ReadonlyArray<ITableBlockViewModel>;
    get groupingColumn(): ViewColumnMetadataSealed | null;
    set groupingColumn(value: ViewColumnMetadataSealed | null);
    get columnSettings(): ColumnSettings;
    get initialized(): boolean;
    createColumnAction: (options: ITableColumnViewModelCreateOptions) => ITableColumnViewModel;
    createRowAction: (options: ITableRowViewModelCreateOptions) => ITableRowViewModel;
    readonly modifyRowActions: EventHandler<(row: ITableRowViewModel) => void>;
    createCellAction: (options: ITableCellViewModelCreateOptions) => ITableCellViewModel;
    createBlockAction: (options: ITableBlockViewModelCreateOptions) => ITableBlockViewModel;
    readonly keyDown: EventHandler<(args: {
        control: TableGridViewModelBase<T>;
        event: React.KeyboardEvent;
    }) => void>;
    get saveTableHeightWhenLoading(): boolean;
    set saveTableHeightWhenLoading(value: boolean);
    isGroupsCollapsed: boolean;
    get wideTableVisibleWidth(): number;
    set wideTableVisibleWidth(value: number);
    get horizontalScroll(): boolean;
    set horizontalScroll(value: boolean);
    initiailize(): void;
    dispose(): void;
    protected initColumns(): void;
    protected isColumnsEquals(columns: ReadonlyMap<string, SchemeDbType>): boolean;
    protected initRows(): void;
    protected initBlocks(): void;
    protected createRow(_data: ReadonlyArray<ReadonlyMap<string, unknown>>, rowData: ReadonlyMap<string, any>, viewMetadata: ViewMetadataSealed, _cellSelectionMode: boolean, columnViewModels: ReadonlyArray<ITableColumnViewModel>, treeId: string | null, treeParentRowId: string | null, isGroup: boolean, isToggle: boolean): ITableRowViewModel;
    protected createCell(row: ITableRowViewModel, column: ITableColumnViewModel, rowData: ReadonlyMap<string, any>): ITableCellViewModel;
    protected setSorting(): void;
    protected getColumnContextMenu: (_column: ITableColumnViewModel) => ReadonlyArray<MenuAction>;
    protected getRowContextMenu: (_row: ITableRowViewModel) => ReadonlyArray<MenuAction>;
    protected getBlockContextMenu: (_block: ITableBlockViewModel) => ReadonlyArray<MenuAction>;
    protected executeInViewContext: (action: (context: IUIContext) => void) => void;
    protected arrangeColumns(resultColumns: ITableColumnViewModel[], metadataColumns: ReadonlyMap<string, ViewColumnMetadataSealed>, columnsOrdering: ColumnInfo[]): void;
    changeColumnOrderByTarget(sourceIndex: number, targetIndex: number): void;
    rebuild(): void;
    abstract getUIContext(): IUIContext;
}
export {};
