import { FC, KeyboardEvent, SyntheticEvent } from 'react';
import { RichTextBoxAttachment, LinkInfo, RichTextBoxAttachmentInnerItemDuplicate } from './common';
import { IColorPalette } from 'ui/colorPicker/';
import { UIButton } from 'tessa/ui';
import { IRichTextCharCounter } from './index';
import { DialogType } from 'tessa/ui/tessaDialog/dialogType';
export interface RichTextBoxProps {
    html?: string;
    autoFocus?: boolean;
    showFocus?: boolean;
    hasReadOnlyMode?: boolean;
    readOnly?: boolean;
    readOnlyMode?: boolean;
    dropDownDirectionUp?: boolean;
    onChange?(html: string): void;
    onChangeReadOnlyMode?(readOnlyMode: boolean): void;
    foregroundPalette: IColorPalette;
    backgroundPalette: IColorPalette;
    blockPalette: IColorPalette;
    attachments?: ReadonlyArray<RichTextBoxAttachment>;
    showFileDialog?(dialogType: DialogType): Promise<readonly File[] | File | null>;
    showLinkDialog?(): Promise<LinkInfo | null>;
    allowInnerAttachmentDuplicates?: boolean;
    onAddInnerItemDuplicate?: (attachment: RichTextBoxAttachmentInnerItemDuplicate[]) => void;
    onAddAttachments?(attachments: RichTextBoxAttachment[]): boolean;
    onRemoveAttachment?(attachment: RichTextBoxAttachment): void;
    onChangeAttachment?(attachment: RichTextBoxAttachment): void;
    onPreviewFileAttachment?(attachment: RichTextBoxAttachment): void;
    onOpenInnerAttachment?: (id: string) => void;
    onOpenFileAttachment?: (id: string) => void;
    onOpenLinkAttachment?: (id: string) => void;
    onLinkClick?: (e: SyntheticEvent, href: string) => void;
    height?: string;
    minHeight?: string;
    maxHeight?: string;
    errorMessage?: string;
    resetHistoryOnImport?: boolean;
    onImportComplete?: () => void;
    hoverButtons?: readonly UIButton[];
    isExpanded?: boolean;
    onCollapse?: () => void;
    onKeyDown?: (event: KeyboardEvent) => void;
    maxListNestingDepth?: number;
    maxCharCount?: number | null;
    charCounter?: IRichTextCharCounter | undefined;
    spellcheck?: boolean;
}
export declare const RichTextBox: FC<RichTextBoxProps>;
