import { ControlViewModelBase } from './controlViewModelBase';
import { CardTypeControl } from 'tessa/cards/types';
import { CardTask } from 'tessa/cards';
import { Visibility } from 'tessa/platform';
export declare class TaskInfoViewModel extends ControlViewModelBase {
    constructor(control: CardTypeControl, task: CardTask, includedInControl: boolean | undefined, executeInContext: Function);
    private _roleId;
    private _authorId;
    private _creatorId;
    private _executeInContext;
    typeCaption: string;
    authorName: string;
    authorVisibility: Visibility;
    creatorName: string;
    creatorVisibility: Visibility;
    get authorOnlyVisibility(): Visibility;
    inProgressUserName: string | null;
    inProgressUserVisibility: Visibility;
    roleNamePrefix: string;
    roleName: string;
    displayRoleName: string;
    roleNavigationCommand: string;
    authorNavigationCommand: string;
    creatorNavigationCommand: string;
    limitationPrefix: string;
    limitation: string;
    limitationExtra: string;
    limitationFontWeight: any;
    limitationTimeZone: string | null;
    performerType: string;
    performerTypeVisibility: Visibility;
    digest: string | null;
    digestVisibility: Visibility;
    firstSeparatorVisibility: Visibility;
    secondSeparatorVisibility: Visibility;
    plannedToolTip: string;
    infoToolTip: string;
    includedInControl: boolean;
    private openCardAsync;
    roleNavigationAction(): void;
    authorNavigationAction(): void;
    creatorNavigationAction(): void;
    private static getAuthorNameAndPosition;
    private static getAuthorVisibility;
    private static getCreatorVisibility;
    private static getInProgressUserVisibility;
    private static getLimitationPrefix;
    private static getLimitation;
    private static getLimitationExtra;
    private static getLimitationFontWeight;
    private static getLimitationTimeZone;
    private static getPerformerType;
    private static getPerformerTypeVisibility;
    private static getRoleNamePrefix;
    private static getDisplayRoleName;
    private static getTypeCaption;
    private getSecondSeparatorVisibility;
    private getInfoToolTip;
}
