<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="2.6.15.0" ID="25ef0098-69a9-4454-94c8-c9a7aa0d3f6f" Name="FullTextSearch">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
	</Dependencies>
	<SchemeTable ID="a03f6c5d-e719-43d6-bcc5-d2ea321765ab" Name="FmMessages" IsExternal="true" />
	<SchemeMigration ID="29ded976-a8e7-4ef2-88ab-10264afdc521" Name="ForumSearchMessages_ms" IsExternal="true" />
	<SchemeMigration ID="45f0634d-cba0-4faf-8286-a9ecc74422f5" Name="ForumSearchMessages_pg" IsExternal="true" />
</SchemePartition>